### ISSUE TITLE
cant unminify simple file both cli & node api

### ISSUE THREAD

**Issue by pabx06** [shapesecurity/unminify#16]
i attached the file
[6.js.gz](https://github.com/shapesecurity/unminify/files/3453556/6.js.gz)

the code is:

```javascript
function (e, t) {
  var n;
  n = function () {
    return this;
  }();
  try {
    n = n || new Function("return this")();
  } catch (e) {
    "object" == typeof window && (n = window);
  }
  e.exports = n;
}
```
even tried to unminify the AST tree parsed from shift

**Comment by bakkot** [comment]
Yes, that's not valid JavaScript. Function declarations need to have names. If you replace `function` with `function main`, it'll run through Unminify successfully (though it doesn't change much).
